### ISSUE TITLE
Inquiry for explanation

### ISSUE THREAD

**Issue by YeongHyeon** [HyeonHo99/DayNight#1]
Hi,

This work is very interesting.
Can I ask you to plan for providing README?
If the above is given, it is highly helpful for watchers who have interested in your work.

Thank you!

(You can close this issue without any action.)

**Comment by HyeonHo99** [comment]
Sure!
I am planning to write README and also commit modifications on this
weekend. I will make sure to write READMe for watchers 👍

2022년 6월 8일 (수) 오전 10:24, YeongHyeon Park ***@***.***>님이 작성:
